#!/usr/bin/env python
# -*- coding: UTF-8 -*-
from django.contrib.sites.models import Site
from django.core.management import call_command
from apps.topic.models import Node
import MySQLdb
import datetime

conn = MySQLdb.connect(host = 'localhost', user = 'pythonic', passwd = 'pythonic')
cursor = conn.cursor()

try:
    cursor.execute('drop database pythonic')
    cursor.execute('create database if not exists pythonic default charset utf8 COLLATE utf8_general_ci')
    #conn.select_db('pythonic')
    conn.commit()
except Exception, e:
    print e

try:
    call_command('syncdb', interactive=True)
except Exception, e:
    print e
    pass

#初始化节点
time = datetime.datetime.now()
new_node = Node(name='Pythonic',slug='pythonic',description=u'pythonic节点',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='分享',slug='share',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='奇思妙想',slug='idea',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='创造',slug='creation',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()

new_node = Node(name='瞎扯谈',slug='chat',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='设计',slug='design',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='TED',slug='ted',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='开源',slug='open-source',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='Ruby',slug='ruby',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='创业',slug='startup',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='Kindle',slug='kindle',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='黑客与画家',slug='kk',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='函数式编程',slug='functional',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='Rework',slug='rework',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='Mac',slug='mac',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='Agile',slug='agile',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='QA测试',slug='testing',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='Lisp',slug='lisp',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='翻墙',slug='gfw',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='招聘',slug='job',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()

new_node = Node(name='Django',slug='django',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='MongoDB',slug='mongodb',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='Redis',slug='redis',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='前端开发',slug='front-end',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='South',slug='south',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='Web安全',slug='web-security',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='RESTful',slug='restful',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='Tornado',slug='tornado',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='云服务',slug='cloud',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='RabbitMQ',slug='rabbitmq',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='Fabric',slug='fabric',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='算法',slug='algorithm',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='Memcached',slug='memcached',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='Flask',slug='flask',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='Git',slug='git',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='web.py',slug='web-py',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='Database',slug='database',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='Linux',slug='linux',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='Nginx',slug='nginx',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='运维',slug='operation',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()

new_node = Node(name='机器学习',slug='ml',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='可视化',slug='visualization',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='OpenStack',slug='openstack',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='自然语言处理',slug='nlp',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='GUI',slug='gui',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()

new_node = Node(name='iOS',slug='ios',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='Android',slug='android',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='HTML5',slug='html5',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()
new_node = Node(name='线下活动',slug='activity',description=u'',num_topics=0,created_on=time,updated_on=time)
new_node.save()

Site.objects.filter(id=1).update(domain='pythonic.org',name='Pythonic社区')